### ISSUE TITLE
stringr not loading

### ISSUE THREAD

**Issue by behrman** [hadley/tidyverse#11]
I'm using tidyverse 1.0.0 and

library(tidyverse)

is not loading stringr.

**Comment by hrbrmstr** [comment]
From `zzz.R`:

    load <- c("ggplot2", "tibble", "tidyr", "readr", "purrr", "dplyr")

Is is supposed to load `stringr`? Looks like it's not supposed to auto-load it but it does ensure it's available for you to use. From the `README`: _"It also installs a selection of other tidyverse packages that you're likely to use frequently, but probably not in every analysis."_ (followed by a list that include `stringr`.

**Comment by behrman** [comment]
I should have read the documentation more closely. Installing tidyverse installs the range of packages listed in the README, but library(tidyverse) only loads the core packages.

Thanks.

**Comment by hadley** [comment]
This has bitten others so please let me know if you think of better wording

**Comment by behrman** [comment]
I’d say the problem could be the mental model many have of packages, together with just quickly skimming the documentation.

Many may think that when they install a package and then load it, they’ll get that package. So they may think that tidyverse is equivalent to the set of packages that it installs, and loading it will load all of them.

Since many may just scan the documentation and not read the details, you may wish to consider something visual, like a table, to distinguish between the packages that are installed vs. those that are loaded.
