### ISSUE TITLE
Error on tidyverse_update()

### ISSUE THREAD

**Issue by jetravis** [hadley/tidyverse#3]
Update produces the following error message after a devtools install.
> tidyverse_update()
Error in FUN(X[[i]], ...) : package ‘psych’ not found

Session info ----------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       RStudio (0.99.903)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2016-09-06                  

Packages --------------------------------------------------------------
 package    * version    date       source                           
 assertthat   0.1        2013-12-06 CRAN (R 3.3.1)                   
 colorspace   1.2-6      2015-03-11 CRAN (R 3.3.1)                   
 DBI          0.5        2016-08-11 CRAN (R 3.3.1)                   
 devtools     1.12.0     2016-06-24 CRAN (R 3.3.1)                   
 digest       0.6.10     2016-08-02 CRAN (R 3.3.1)                   
 dplyr      * 0.5.0      2016-06-24 CRAN (R 3.3.1)                   
 ggplot2    * 2.1.0      2016-03-01 CRAN (R 3.3.1)                   
 gtable       0.2.0      2016-02-26 CRAN (R 3.3.1)                   
 magrittr     1.5        2014-11-22 CRAN (R 3.3.1)                   
 memoise      1.0.0      2016-01-29 CRAN (R 3.3.1)                   
 munsell      0.4.3      2016-02-13 CRAN (R 3.3.1)                   
 plyr         1.8.4      2016-06-08 CRAN (R 3.3.1)                   
 purrr      * 0.2.2      2016-06-18 CRAN (R 3.3.1)                   
 R6           2.1.3      2016-08-19 CRAN (R 3.3.1)                   
 Rcpp         0.12.6     2016-07-19 CRAN (R 3.3.1)                   
 readr      * 1.0.0      2016-08-03 CRAN (R 3.3.1)                   
 rsconnect    0.4.3      2016-05-02 CRAN (R 3.3.1)                   
 scales       0.4.0      2016-02-26 CRAN (R 3.3.1)                   
 tibble     * 1.2        2016-08-26 CRAN (R 3.3.1)                   
 tidyr      * 0.6.0      2016-08-12 CRAN (R 3.3.1)                   
 tidyverse  * 0.0.0.9000 2016-09-06 Github (hadley/tidyverse@2903dbc)
 withr        1.0.2      2016-06-20 CRAN (R 3.3.1)

**Comment by hadley** [comment]
What does `install.packages("psych")` do?

**Comment by jetravis** [comment]
Installs the package.

**Comment by jetravis** [comment]
Installs the package.

**Comment by hadley** [comment]
What does `install.packages("psych")` do?

**Comment by hadley** [comment]
I'm not sure how you could load tidyverse without pysch already installed - it's a dependency of broom.

**Comment by hadley** [comment]
I'm not sure how you could load tidyverse without pysch already installed - it's a dependency of broom.

**Comment by jetravis** [comment]
I just removed broom, psych and tidyverse and tried reinstalling using install_github. Somehow tidyverse installs broom without psych. Here is the result of library for tidyverse and broom

> library(tidyverse)
Loading tidyverse: ggplot2
Loading tidyverse: tibble
Loading tidyverse: tidyr
Loading tidyverse: readr
Loading tidyverse: purrr
Loading tidyverse: dplyr
Conflicts with tidy packages -----------------------------------------------------------------------------------------------------------------------
filter(): dplyr, stats
lag():    dplyr, stats
> library("broom", lib.loc="~/R/win-library/3.3")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘psych’
Error: package or namespace load failed for ‘broom’

**Comment by jetravis** [comment]
And here is the tidyverse install results

> devtools::install_github("hadley/tidyverse")
Downloading GitHub repo hadley/tidyverse@master
from URL https://api.github.com/repos/hadley/tidyverse/zipball/master
Installing tidyverse
"C:/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/jetravis/AppData/Local/Temp/RtmpQnKOAk/devtools4ac0387a4757/hadley-tidyverse-c38eccb"  \
  --library="C:/Users/jetravis/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'tidyverse' ...
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
Conflicts with tidy packages ---------------------------------------------------
*** arch - x64
Conflicts with tidy packages ---------------------------------------------------
* DONE (tidyverse)

**Comment by hadley** [comment]
Hmmm, this seems like a devtools bug. Would you mind filing it there?
