### ISSUE TITLE
devtools, roxygen2 & testthat

### ISSUE THREAD

**Issue by benmarwick** [hadley/tidyverse#9]
Do you have any plans to include these very useful pkgs? Maybe something like a dev branch on this repo that is the tidyverse plus the other three pkgs, or some variation on `dev_mode(on=TRUE)`?

**Comment by hadley** [comment]
No, just because they're not part of the tidyverse as they're to do with package development rather than data analysis. I'm planning to work on a similar naming and bundling for the package dev tools.

**Comment by benmarwick** [comment]
OK, thanks! I look forward to seeing that next project.
